version: "3"
services:
  native:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 19006:19006
    volumes:
      - ./App.js:/app/App.js
      - /app/node_modules/